# Generated by staticlp / scripts/New-NetlifyCampaign.ps1 — edit copy, presenter, file_id, analytics.
# form_name must be unique per Netlify site. Form action = paths.thank_you (avoid 301 on POST).

id = "__CAMPAIGN_ID__"
form_name = "__FORM_NAME__"
honeypot_field = "bot-field"

submit_label = "Get the materials"
consent_text = "By submitting, you agree to receive the material by email and occasional messages about this content. You can unsubscribe anytime."

qr_delay_ms = 1400
qr_meta_refresh_sec = 6
thank_you_redirect_ms = 1000

[paths]
thank_you = "/__LANG__/__SLUG__/obrigado/"
material = "/__LANG__/__SLUG__/material/"
landing = "/__LANG__/__SLUG__/"

[delivery]
type = "google_drive_pdf"
file_id = "REPLACE_WITH_FILE_ID"
preview_url = ""
direct_url = ""

[presenter]
name = "Your name"
headline = "Short headline"
bio = "One or two sentence bio."
photo = "profile.jpg"
linkedin_url = "https://www.linkedin.com/in/"

[analytics]
body_class = "analytics-campaign-__SLUG__"
campaign = "__SLUG__-funnel"

[[fields]]
name = "name"
label = "Name"
type = "text"
required = true
autocomplete = "name"

[[fields]]
name = "email"
label = "Email"
type = "email"
required = true
autocomplete = "email"
inputmode = "email"
